### ISSUE TITLE
URL não abre o video

### ISSUE THREAD

**Issue by dungeon2567** [scriptcaser/SigeoCam#2]
Ao clicar no link que recebi pelo whatsapp o video do outro peer não é aberto.

**Comment by scriptcaser** [comment]
Você configurou o nginx? As rotas certinhas? Ou tá rodando em localhost?

Nãose esqueça depoisque compartilhar voltar o vídeo

**Comment by dungeon2567** [comment]
estou usando esse link: https://webrtc.scriptcaser.com/

**Comment by scriptcaser** [comment]
Testei e tranquilo, verifique configurações no seu firewall

**Comment by dungeon2567** [comment]
Resolvido, era problema na url que vem do whatsapp. Eu acho que ela que tem um bug =/

vlw

**Comment by dungeon2567** [comment]
Resolvido
